### ISSUE TITLE
UndefVarError: concrete_bridge_type not defined

### ISSUE THREAD

**Issue by makoto-yamashita** [JuliaOpt/PolyJuMP.jl#48]
Thank you very much for the useful package.

Recently, I have updated PolyJuMP.jl and other Julia packages, but then I am stuck with the following error.

julia> using PolyJuMP
[ Info: Precompiling PolyJuMP [ddf597a6-d67e-5340-b84c-e37d84115374]
ERROR: LoadError: LoadError: UndefVarError: concrete_bridge_type not defined

I am using Julia v1.2.0 on Debian Linux.
If there is something I had better check, I would like to share such information.

**Comment by blegat** [comment]
There is no released version compatible with JuMP v0.20 and MOI v0.9. You should use the master branch of PolyJuMP and SumOfSquares until they are released (which should be in a day or two).

**Comment by makoto-yamashita** [comment]
Thank you very much for your comment.
I am now using the master branch as follows, and it works well.

(v1.2) pkg> add PolyJuMP#master
(v1.2) pkg> add SumOfSquares#master

Thank you very much again.

**Comment by blegat** [comment]
This was resolved by the v0.3 releases
